[tool.black]
line-length = 99
skip-numeric-underscore-normalization = true
include = '\.pyi?$'
exclude = '''
/(
    \.git
)/
'''

[tool.isort]
force_grid_wrap = 0
include_trailing_comma = true
known_first_party = 'cloudy,core'
known_third_party = ["django", "import_export"]
line_length = 99
multi_line_output = 3
skip_glob = ''
use_parentheses = true
combine_as_imports = true

# If set, imports will be sorted within their section independent to the import_type.
# force_sort_within_sections = true

known_django = 'django'
known_django_contrib = 'redis_cache'

sections = 'FUTURE,STDLIB,THIRDPARTY,DJANGO,DJANGO_CONTRIB,FIRSTPARTY,LOCALFOLDER'
