# Generated by Django 4.1.2 on 2023-03-13 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_visit', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitemedicale',
            old_name='date_mise_a_jour',
            new_name='update_date',
        ),
    ]
