# Generated by Django 4.1.2 on 2023-03-13 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_visit', '0002_rename_date_mise_a_jour_visitemedicale_update_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitemedicale',
            old_name='montant',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='visitemedicale',
            old_name='animaux',
            new_name='animals',
        ),
        migrations.RenameField(
            model_name='visitemedicale',
            old_name='commentaire',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='visitemedicale',
            old_name='veterinaire',
            new_name='veterinary',
        ),
        migrations.RenameField(
            model_name='visitemedicale',
            old_name='type_visite',
            new_name='visit_type',
        ),
    ]
