# Generated by Django 4.1.2 on 2023-03-13 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_association', '0018_delete_visitemedicale'),
        ('medical_visit', '0003_rename_montant_visitemedicale_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitemedicale',
            name='animals',
            field=models.ManyToManyField(db_table='gestion_association_visitemedicale_animaux', related_name='visites', to='gestion_association.animal', verbose_name='Animaux'),
        ),
        migrations.AlterField(
            model_name='visitemedicale',
            name='comment',
            field=models.CharField(blank=True, max_length=2000, verbose_name='Commentaire'),
        ),
        migrations.AlterField(
            model_name='visitemedicale',
            name='veterinary',
            field=models.CharField(blank=True, max_length=150, verbose_name='Vétérinaire'),
        ),
    ]
