# Generated by Django 4.1.2 on 2023-05-07 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_visit', '0004_alter_visitemedicale_animals_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitemedicale',
            name='visit_type',
            field=models.CharField(choices=[('VAC_PRIMO_TC', 'Primo vaccination TC'), ('VAC_PRIMO_TCL', 'Primo vaccination TCL'), ('VAC_RAPPEL_TC', 'Rappel vaccination TC'), ('VAC_RAPPEL_TCL', 'Rappel vaccination TCL'), ('STE', 'Stérilisation'), ('TESTS', 'Tests FIV/FELV'), ('IDE', 'Identification'), ('CONSULT', 'Consultation'), ('PACK_TC', 'Identification, primo vaccination TC, Tests FIV/FELV'), ('PACK_TCL', 'Identification, primo vaccination TCL, Tests FIV/FELV'), ('PACK_STE_TC', 'Stérilisation, Identification, primo vaccination TC, Tests FIV/FELV'), ('PACK_STE_TCL', 'Stérilisation, Identification, primo vaccination TCL, Tests FIV/FELV'), ('AUTRE', 'Autre'), ('CHIRURGIE', 'Chirurgie'), ('URGENCE', 'Urgence'), ('TRAITEMENT', 'Traitement')], max_length=30, verbose_name='Objet de la visite'),
        ),
    ]
