# Generated by Django 4.1.2 on 2025-06-30 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_visit', '0005_alter_visitemedicale_visit_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitemedicale',
            name='amount_animal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Montant par animal'),
        ),
    ]
