# Generated by Django 3.1.4 on 2022-01-03 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_association', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonsterilisation',
            name='veterinaire',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
