# Generated by Django 3.1.4 on 2021-04-11 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_association", "0002_accueil"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accueil",
            name="date_fin",
            field=models.DateField(blank=True, null=True, verbose_name="Date de fin"),
        ),
    ]
