# Generated by Django 3.1.4 on 2022-01-03 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_association', '0002_bonsterilisation_veterinaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_adherent',
            field=models.BooleanField(default=False, verbose_name='Adhérent(e)'),
        ),
        migrations.AddField(
            model_name='person',
            name='is_ancien_proprio',
            field=models.BooleanField(default=False, verbose_name='Ancien propriétaire'),
        ),
        migrations.AddField(
            model_name='person',
            name='is_parrain',
            field=models.BooleanField(default=False, verbose_name='Parrainage'),
        ),
        migrations.CreateModel(
            name='Parrainage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('type_paiement', models.CharField(choices=[('MENSUEL', 'Mensuel'), ('UNIQUE', 'En une fois')], default='MENSUEL', max_length=20, verbose_name='Type de paiement')),
                ('montant', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Montant du parrainage')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_association.animal')),
                ('personne', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_association.person')),
            ],
        ),
        migrations.CreateModel(
            name='Adhesion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentaire', models.CharField(blank=True, max_length=500, verbose_name='Commentaire adhésion')),
                ('date', models.DateField(blank=True, null=True, verbose_name="Date d'adhésion")),
                ('montant', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Montant de la cotisation')),
                ('personne', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_association.person', verbose_name='Personne')),
            ],
        ),
    ]
