# Generated by Django 3.1.4 on 2022-01-04 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_association', '0003_auto_20220103_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='famille',
            name='statut',
            field=models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('OCCUPE', 'Occupée'), ('A_VISITER', 'A visiter'), ('INDISPONIBLE', 'Temporairement indisponible'), ('INACTIVE', 'Inactive'), ('ADHESION', 'Attente adhésion')], default='A_VISITER', max_length=20, verbose_name='Statut'),
        ),
    ]
