# Generated by Django 3.1.4 on 2022-01-05 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_association', '0004_auto_20220104_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='nekosable',
            field=models.BooleanField(default=False, verbose_name='Nekosable'),
        ),
    ]
