# Generated by Django 3.1.4 on 2022-01-08 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_association', '0005_animal_nekosable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='nom',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='nom_prenom_key',
            field=models.CharField(blank=True, max_length=150, unique=True),
        ),
    ]
