# Generated by Django 3.1.4 on 2022-01-09 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_association', '0006_auto_20220108_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='ancien_proprio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='anciens_animaux', to='gestion_association.person', verbose_name='Ancien propriétaire'),
        ),
    ]
