# Generated by Django 3.1.4 on 2022-01-13 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_association', '0007_animal_ancien_proprio'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='inactif',
            field=models.BooleanField(default=False, verbose_name="Desactivé (Ne cocher que si vous ne souhaitez                                           plus gérer cet animal dans l'application) "),
        ),
    ]
