# Generated by Django 3.1.4 on 2022-02-11 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_association', '0010_auto_20220206_0459'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitemedicale',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='visitemedicale',
            name='type_visite',
            field=models.CharField(choices=[('VAC_PRIMO_TC', 'Primo vaccination TC'), ('VAC_PRIMO_TCL', 'Primo vaccination TCL'), ('VAC_RAPPEL_TC', 'Rappel vaccination TC'), ('VAC_RAPPEL_TCL', 'Rappel vaccination TCL'), ('STE', 'Stérilisation'), ('TESTS', 'Tests FIV/FELV'), ('IDE', 'Identification'), ('CONSULT', 'Consultation'), ('PACK_TC', 'Identification, primo vaccination TC, Tests FIV/FELV'), ('PACK_TCL', 'Identification, primo vaccination TCL, Tests FIV/FELV'), ('AUTRE', 'Autre'), ('CHIRURGIE', 'Chirurgie'), ('URGENCE', 'Urgence')], max_length=30, verbose_name='Objet de la visite'),
        ),
    ]
