# Generated by Django 3.1.4 on 2022-03-20 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_association', '0012_auto_20220212_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='perimetre',
            field=models.CharField(choices=[('UN', 'Périmètre 1 (Marjo)'), ('DEUX', 'Périmètre 2 (Lucile)')], default='UN', max_length=30, verbose_name='Périmètre de gestion'),
        ),
        migrations.AddField(
            model_name='famille',
            name='perimetre',
            field=models.CharField(choices=[('UN', 'Périmètre 1 (Marjo)'), ('DEUX', 'Périmètre 2 (Lucile)')], default='UN', max_length=30, verbose_name='Périmètre de gestion'),
        ),
    ]
