# Generated by Django 3.1.4 on 2022-06-27 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_association', '0013_auto_20220320_0936'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accueil',
            options={'ordering': ['-date_debut']},
        ),
    ]
