# Generated by Django 3.1.4 on 2022-09-18 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_association', '0014_auto_20220627_0654'),
    ]

    operations = [
        migrations.AddField(
            model_name='parrainage',
            name='date_nouvelles',
            field=models.DateField(blank=True, null=True, verbose_name='Date des dernières nouvelles données'),
        ),
    ]
