# Generated by Django 3.1.4 on 2022-09-19 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_association', '0015_parrainage_date_nouvelles'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='contact',
            field=models.CharField(blank=True, max_length=500, verbose_name='Contact prise en charge'),
        ),
    ]
