# Generated by Django 4.1.2 on 2023-03-12 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_association', '0016_animal_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parrainage',
            options={'ordering': ['-date_debut']},
        ),
    ]
