# Generated by Django 4.1.2 on 2023-05-07 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_association', '0018_delete_visitemedicale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='statut',
            field=models.CharField(choices=[('A_ADOPTER', "A l'adoption"), ('ADOPTABLE', 'Adoptable'), ('ADOPTION', "En cours d'adoption"), ('SOCIA', 'Sociabilisation'), ('ADOPTE', 'Adopté'), ('ADOPTE_DEFINITIF', 'Adopté définitivement'), ('QUARANTAINE', 'Quarantaine'), ('SOIN', 'En soin'), ('SEVRAGE', 'En sevrage'), ('PERDU', 'Perdu'), ('DECEDE', 'Décédé'), ('RENDU', 'Rendu à ses propriétaires'), ('RELACHE', 'Relâché'), ('PEC', 'Prendre en charge'), ('ALLAITANTE', 'Allaitante')], default='QUARANTAINE', max_length=30),
        ),
    ]
