# Generated by Django 4.1.2 on 2024-05-17 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_association', '0021_alter_animal_perimetre_alter_famille_perimetre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='nekosable',
        ),
        migrations.RemoveField(
            model_name='famille',
            name='neko',
        ),
    ]
