# Generated by Django 4.1.2 on 2025-09-17 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_association', '0022_remove_animal_nekosable_remove_famille_neko'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='perimetre',
            field=models.CharField(choices=[('UN', 'Périmètre 1 (Marjo)'), ('DEUX', 'Périmètre 2 (Lucile)'), ('TROIS', 'Périmètre 3 (Mélanie)'), ('QUATRE', 'Périmètre 4 (Julie)'), ('CINQ', 'Périmètre 5 (Clémence)')], default='UN', max_length=30, verbose_name='Périmètre de gestion'),
        ),
        migrations.AlterField(
            model_name='famille',
            name='perimetre',
            field=models.CharField(choices=[('UN', 'Périmètre 1 (Marjo)'), ('DEUX', 'Périmètre 2 (Lucile)'), ('TROIS', 'Périmètre 3 (Mélanie)'), ('QUATRE', 'Périmètre 4 (Julie)'), ('CINQ', 'Périmètre 5 (Clémence)')], default='UN', max_length=30, verbose_name='Périmètre de gestion'),
        ),
    ]
