# Generated by Django 4.1.2 on 2025-12-30 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_association', '0023_alter_animal_perimetre_alter_famille_perimetre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='famille',
            name='statut',
            field=models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('OCCUPE', 'Occupée'), ('A_VISITER', 'A visiter'), ('INDISPONIBLE', 'Temporairement indisponible'), ('INACTIVE', 'Inactive'), ('ADHESION', 'Attente adhésion'), ('A_SORTIR', 'A sortir de la BNO')], default='A_VISITER', max_length=20, verbose_name='Statut'),
        ),
    ]
