# Generated by Django 4.1.2 on 2026-03-15 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_association', '0024_alter_famille_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='perimetre',
            field=models.CharField(choices=[('UN', 'Périmètre 1 (Marjo)'), ('DEUX', 'Périmètre 2 (Lucile)'), ('TROIS', 'Périmètre 3 (Mélanie)'), ('QUATRE', 'Périmètre 4 (Julie)'), ('CINQ', 'Périmètre 5 (Clémence)'), ('SIX', 'Périmètre 6 (Maude)')], default='UN', max_length=30, verbose_name='Périmètre de gestion'),
        ),
        migrations.AlterField(
            model_name='famille',
            name='perimetre',
            field=models.CharField(choices=[('UN', 'Périmètre 1 (Marjo)'), ('DEUX', 'Périmètre 2 (Lucile)'), ('TROIS', 'Périmètre 3 (Mélanie)'), ('QUATRE', 'Périmètre 4 (Julie)'), ('CINQ', 'Périmètre 5 (Clémence)'), ('SIX', 'Périmètre 6 (Maude)')], default='UN', max_length=30, verbose_name='Périmètre de gestion'),
        ),
    ]
